### ISSUE TITLE
Средства не пришли на кошелек

### ISSUE THREAD

**Issue by Art188-byte** [apoelstra/coinjoin#11]
Здравствуйте! Отправил депозит на биткой миксер coinjoin средства до меня так и не дошли, помогите разобраться.

**Comment by Art188-byte** [comment]
Сайтом пользовался https://coinjoin.io/ru

**Comment by Art188-byte** [comment]
Почти сутки прошли, средства так и не поступили мне на кошелек

**Comment by Enfernuz** [comment]
**[en]** coinjoin.io is a scam website and has no relation to the repository despite having a link on it. I'm sorry to say that but you've lost your funds to scammers. Shit happens, I myself have been scammed before in another even less complicated scheme and it taught me something. I hope it was a small amount and please be more vigilant in the future.

**[ru]** coinjoin.io - это мошеннический веб-сайт, который не имеет никакого отношения к данному репозиторию, несмотря на то, что содержит ссылку на него. Я сожалею, но Ваши средства украдены мошенниками. Никто не застрахован - я тоже был жертвой мошенников в другой, даже ещё менее сложной схеме, но это меня кое-чему научило. Надеюсь, это была не большая для Вас сумма, так что, пожалуйста, будьте более бдительны в дальнейшем.
