### ISSUE TITLE
Transaction not completed after confirmation

### ISSUE THREAD

**Issue by leo-lax** [apoelstra/coinjoin#12]
Hello, there

My coinjoin ID is 8BTE0W

My transaction is at 16 confirmations but still pending deposit on coinjoin. How do I check the status of it?

**Comment by apoelstra** [comment]
I do not run any coinjoin service -- this repository contains some old software which is not hosted anywhere as far as I know. The software doesn't have any notion of "coinjoin ID".

Unfortunately, I suspect you have sent your coins to a scam website (see the README on this repo or the project description). There is nothing I can do in this case.

**Comment by leo-lax** [comment]
thank you I appreciate!
