### ISSUE TITLE
Bug when recieving money

### ISSUE THREAD

**Issue by linxtuga** [apoelstra/coinjoin#3]
Hello,

I've requested on coinjoin to send money to a certain address and it awaited confirmations. The truth is, I've actually verified that it confirmed already at qrs54r3ystkr9de7tnjge0ytnajujswphvlwj0s8s9 but the money wasn't sent to the final destination I've inserted, never arrived. So I was looking forward to whether it could be returned to the original sending point, or forward to the final address I've wanted to.

Thanks.

**Comment by apoelstra** [comment]
This is not a repo for any public-facing service.

I suspect, from other bug reports, that you have been scammed by coin join dot io. I'm sorry for your loss but this has nothing to do with me and there is nothing I can do.
