### ISSUE TITLE
Lost coins on CoinJoin

### ISSUE THREAD

**Issue by Coinbug** [apoelstra/coinjoin#7]
Hi, I used Coinjoin Friday at around 2:48AM Friday, and never received my coins back. Help please!

**Comment by Coinbug** [comment]
If you don't send it back I will report you to Google and you will be removed forever. My friend's wife works there (high position) and she will make sure you're taken down. I will wait 2 hours, and if the BTC is not returned you best be planning for retirement ;) 

Have fun deciding :D 

I sent you 0.0112 BTC from bc1q36lwtnamdnfvs64g8080w5zdgzhnuxpe8qsnqp.

**Comment by Coinbug** [comment]
I've reconsidered, in case you don't see this in time: I'll wait until noon on Monday (ET)

**Comment by smallzhong** [comment]
dude, read the readme.

**A note about coinjoin.io:** coinjoin dot io is a scam. Not in an exaggerated
or metaphorical sense. I mean that it will simply take your money and not
return it.

**This repo has nothing to do with that site. I have nothing to do with that site.
If you are victimized by it there is nothing that I can do for you.**

The same applies to coinjoin.cash, unlockingblockchainafrica.io, and **any website
claiming to be associated with this repo**. This repo is not a website.

**Comment by apoelstra** [comment]
Thanks @smallzhong. Yes, @Coinbug this is addressed in the README. I'm sorry for your loss.

Best of luck removing me from Google.

**Comment by Coinbug** [comment]
Hi apoelstra,
Do you have any idea why CoinJoin is linked to this page?
Also, I'll take down CoinJoin, not this page, of course. 
Thanks

**Comment by apoelstra** [comment]
I presume these scammers link to me in an attempt to fraudulently borrow my reputation. They are anonymous fly-by-nights, and there is not much I can do about it.

**Comment by Coinbug** [comment]
Think FBI would take them down? Do you think it's worth it to report the site?
Also, what introductory bitcoin material would be best suited for a businessman. I'm trying to introduce it to some people. For their benefit. Any thoughts are appreciated....

**Comment by apoelstra** [comment]
I encourage you to report it to the FBI, but no, I do not think they'll take notice unless it fits into some larger crime ring that they're investigating.

As for introductory Bitcoin material, I don't know about business people in particular, but https://www.weusecoins.org/ is always a good place to start I think.

**Comment by Coinbug** [comment]
Thanks, apoelstra!
