### ISSUE TITLE
Didn't get my BTC.

### ISSUE THREAD

**Issue by eryonas** [apoelstra/coinjoin#9]
Hi there. The address that you gave me to send my BTC  to you was bc1q2hzf3axtj2jcmpsvtg3u3llg7706hvep5yn5sn.. The address that I gave you to send  my BTC was  bc1qsffhh4amnm2c8hgfd3cjekln3nfez4yqm5vc8q And. I didn't still get it. If it's something wrong -send my BTC to address from which I deposited to

**Comment by apoelstra** [comment]
I did not give you anything.

You have been scammed, but I am not the scammer. I'm sorry but there is very little likehood that you will see your coins again. See the README or "About" section on this repo.

**Comment by eryonas** [comment]
how did i get scammed? i went on coinjoin.io.

**Comment by apoelstra** [comment]
That is a scam website which encourages users to send funds, but does not return them.

**Comment by eryonas** [comment]
but first time i got 100$ ))

**Comment by eryonas** [comment]
now understood ,thanks. got an experience)

**Comment by eryonas** [comment]
thanks god. I have more. and this scammer done all the best)) next tranсhe would be nearly 100k. (

**Comment by apoelstra** [comment]
Yikes! Glad you caught it early then.

**Comment by Art188-byte** [comment]
Здравствуйте! Помогите пожалуйста разобраться с транзакцией:  bc1q7kgzl4glnzp42wgzz20n0dvwwad6w2j89z0nk9
0.05921691 BTC

**Comment by Art188-byte** [comment]
> Это мошеннический сайт, который призывает пользователей отправлять средства, но не возвращает их.

Помогите разобраться с транзакцией

**Comment by Art188-byte** [comment]
Какой Ваш официальный сайт?
